# Site settings
title: Revealing Hour Creations
email: info@revealinghour.in
description: "A technology blog of people at Revealing Hour Creations."
baseurl: ""
subdomain: "blog."
protocol: "http://"
url: "revealinghour.in"
username: revealinghourcreations
tusername: revealinghour
# Build settings
markdown: kramdown
permalink: pretty

authors:
  nishant:
    name: Nishant Modak
    email: nm@revealinghour.in
    web: http://revealinghour.in
    twitter: nishantmodak
    github: nishantmodak
    gplus: 113216468166310044595/

  siddhartha:
    name: Siddhartha Bhagwan
    email: siddhartha@revealinghour.in
    web: http://revealinghour.in
    twitter: siddhartha_b
    github: siddharthbhagwan
    gplus: 112090768589373334161/

  anuj:
    name: Anuj Deshpande
    email: anuj@revealinghour.in
    web: http://revealinghour.in
    twitter: anujdeshpandey
    github: anujdeshpande
    gplus: 100901027779989154764/
