# Site settings
title: Revealing Hour Creations
email: info@revealinghour.in
description: "A technology blog of people at Revealing Hour Creations."
baseurl: ""
url: "http://revealinghour.in"
username: revealinghourcreations
tusername: revealinghour
# Build settings
markdown: kramdown
permalink: pretty

authors:
  nishant:
    name: Nishant Modak
    email: nm@revealinghour.in
    web: http://revealinghour.in
    twitter: nishantmodak
    github: nishantmodak

  siddhartha:
    name: Siddhartha Bhagwan
    email: siddhartha@revealinghour.in
    web: http://revealinghour.in
    twitter: siddhartha_b
    github: siddharthbhagwan
