# Site settings
title: Revealing Hour Creations
email: info@revealinghour.in
description: "A technology blog of people at Revealing Hour Creations."
baseurl: ""
url: "http://revealinghour.in"
username: revealinghourcreations
tusername: revealinghour
# Build settings
markdown: kramdown
permalink: pretty
